language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

sudo: false

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

script:
- ./vendor/bin/phpunit ./tests/
