language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

sudo: false

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

script:
- ./vendor/bin/phpcs --standard=PSR2 ./src -v
- ./vendor/bin/phpcpd ./src
- ./vendor/bin/phpunit ./tests/ --coverage-clover build/logs/clover.xml
- ./vendor/bin/phpmd ./src text ./phpmd.xml
- ./vendor/bin/security-checker security:check ./composer.lock
